#!/bin/sh

BROOT="build/bundled"
BPROJ="${BROOT}"

DPROJ="../zoliqe.github.io/remotig"

echo "const selectedConnector = 'k2-webrtc'" > src/select-connector.js
ln -fs polymer-remotig.json polymer.json
polymer build

echo "FIXME! replace URLs in smartceiver-app.html: /smartceiver/:page, /smartceiver/tune, /smartceiver/settings, /smartceiver/cwmem"

echo "Deploying to $DPROJ"
[ -d "$DPROJ" ] || mkdir "$DPROJ"
[ -d "$DPROJ/src" ] || mkdir "$DPROJ/src"
[ -d "$DPROJ/bower_components" ] || mkdir "$DPROJ/bower_components"
cp ${BPROJ}/src/smartceiver-app.html ${DPROJ}/src/
cp ${BPROJ}/index-remotig.html ${DPROJ}/index.html
cp ${BPROJ}/manifest.json ${DPROJ}/
cp ${BROOT}/bower.json ${DPROJ}/
cp ${BROOT}/service-worker.js ${DPROJ}/
cp -r ${BPROJ}/images ${DPROJ}/
cp -r ${BROOT}/bower_components/webcomponentsjs ${DPROJ}/bower_components/
cp -r ext/webrtc/* ${DPROJ}/
